//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataRecovery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank
    {
        public Bank()
        {
            this.SystemBankAccount = new HashSet<SystemBankAccount>();
            this.UserBankAccount = new HashSet<UserBankAccount>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string URL { get; set; }
        public int Status { get; set; }
        public string ICONURL { get; set; }
    
        public virtual ICollection<SystemBankAccount> SystemBankAccount { get; set; }
        public virtual ICollection<UserBankAccount> UserBankAccount { get; set; }
    }
}
