//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataRecovery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BetOrder
    {
        public BetOrder()
        {
            this.FollowOrder = new HashSet<FollowOrder>();
            this.PlayTogether = new HashSet<PlayTogether>();
        }
    
        public long Id { get; set; }
        public long UserId { get; set; }
        public int LotteryId { get; set; }
        public long OpenSequence { get; set; }
        public int PlayingMethodId { get; set; }
        public int BetTimes { get; set; }
        public string Content { get; set; }
        public int BetCent { get; set; }
        public int WinCent { get; set; }
        public int Rebate { get; set; }
        public int BetMode { get; set; }
        public int Status { get; set; }
        public Nullable<int> WinFlag { get; set; }
        public System.DateTime OrderTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<long> UpdateUserId { get; set; }
        public int UserCurrentRebate { get; set; }
        public string PrizeModeFull { get; set; }
    
        public virtual Lottery Lottery { get; set; }
        public virtual PlayingMethod PlayingMethod { get; set; }
        public virtual ICollection<FollowOrder> FollowOrder { get; set; }
        public virtual ICollection<PlayTogether> PlayTogether { get; set; }
    }
}
