//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataRecovery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerService
    {
        public long Id { get; set; }
        public long UserId { get; set; }
        public long UserIdAnsweredBy { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
    }
}
