//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataRecovery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InnerLotteryOpenTime
    {
        public int LotteryId { get; set; }
        public long OpenSequence { get; set; }
        public int OpenHour { get; set; }
        public int OpenMinute { get; set; }
        public int DaysAddSequence { get; set; }
    
        public virtual Lottery Lottery { get; set; }
    }
}
