//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataRecovery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LotteryOpen
    {
        public int LotteryId { get; set; }
        public long OpenningSequence { get; set; }
        public int OpenMode { get; set; }
        public long UserId { get; set; }
        public string OpenningNumbers { get; set; }
        public System.DateTime CreatedTime { get; set; }
    
        public virtual Lottery Lottery { get; set; }
    }
}
