//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataRecovery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lottery
    {
        public Lottery()
        {
            this.BetOrder = new HashSet<BetOrder>();
            this.InnerLotteryOpenTime = new HashSet<InnerLotteryOpenTime>();
            this.LotteryOpen = new HashSet<LotteryOpen>();
            this.LotteryPlayingMethodPrize = new HashSet<LotteryPlayingMethodPrize>();
        }
    
        public int Id { get; set; }
        public int CategoryId { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public int Status { get; set; }
        public int OpenMode { get; set; }
        public int OpenNumberCount { get; set; }
        public int StartNumber { get; set; }
        public int EndNumber { get; set; }
        public int MaxSequence { get; set; }
        public long NextOpenSequence { get; set; }
        public int PrizeMoney { get; set; }
        public int OpenDelaySeconds { get; set; }
        public int MaxPrize { get; set; }
        public int MaxPrizeRebate { get; set; }
        public int MinPrize { get; set; }
        public int MinPrizeRebate { get; set; }
    
        public virtual ICollection<BetOrder> BetOrder { get; set; }
        public virtual ICollection<InnerLotteryOpenTime> InnerLotteryOpenTime { get; set; }
        public virtual LotteryCategory LotteryCategory { get; set; }
        public virtual ICollection<LotteryOpen> LotteryOpen { get; set; }
        public virtual LotteryOpenTime LotteryOpenTime { get; set; }
        public virtual ICollection<LotteryPlayingMethodPrize> LotteryPlayingMethodPrize { get; set; }
    }
}
