//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataRecovery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LotteryPlayingMethodPrize
    {
        public int Id { get; set; }
        public int LotteryId { get; set; }
        public int PlayingMethodId { get; set; }
        public int PrizeMoney { get; set; }
        public int Status { get; set; }
    
        public virtual Lottery Lottery { get; set; }
        public virtual PlayingMethod PlayingMethod { get; set; }
    }
}
