//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataRecovery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public Message()
        {
            this.UserMessage = new HashSet<UserMessage>();
        }
    
        public long Id { get; set; }
        public long SenderId { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public int Category { get; set; }
    
        public virtual ICollection<UserMessage> UserMessage { get; set; }
    }
}
