//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataRecovery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlatformDividend
    {
        public long UserId { get; set; }
        public int Month { get; set; }
        public Nullable<int> ProfitCent { get; set; }
        public Nullable<int> ReturnCentFromLower { get; set; }
        public Nullable<int> LowerProfitCent { get; set; }
        public int Status { get; set; }
        public System.DateTime StatusTime { get; set; }
    }
}
