//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataRecovery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayTogether
    {
        public PlayTogether()
        {
            this.UserPlayTogetherRecord = new HashSet<UserPlayTogetherRecord>();
        }
    
        public long Id { get; set; }
        public long BetOrderId { get; set; }
        public bool Publiced { get; set; }
        public int Rebate { get; set; }
        public Nullable<int> WinCent { get; set; }
        public long UserId { get; set; }
        public string WinPercent { get; set; }
        public System.DateTime OrderTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    
        public virtual BetOrder BetOrder { get; set; }
        public virtual ICollection<UserPlayTogetherRecord> UserPlayTogetherRecord { get; set; }
    }
}
