//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataRecovery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServerTime
    {
        public int Id { get; set; }
        public System.DateTime LotteryServerTime { get; set; }
        public System.DateTime LocalTime { get; set; }
    }
}
