//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataRecovery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemBankAccount
    {
        public int Id { get; set; }
        public int BankId { get; set; }
        public string AccountNo { get; set; }
        public string AccountName { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public int Status { get; set; }
    
        public virtual Bank Bank { get; set; }
    }
}
