//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataRecovery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserBankAccount
    {
        public UserBankAccount()
        {
            this.UserIncome = new HashSet<UserIncome>();
            this.WithdrawDeposit = new HashSet<WithdrawDeposit>();
        }
    
        public int Id { get; set; }
        public long UserId { get; set; }
        public int BankId { get; set; }
        public string AccountNo { get; set; }
        public string AccountName { get; set; }
        public int Status { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual ICollection<UserIncome> UserIncome { get; set; }
        public virtual ICollection<WithdrawDeposit> WithdrawDeposit { get; set; }
    }
}
