//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataRecovery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPlayTogetherRecord
    {
        public long Id { get; set; }
        public long PlayTogetherId { get; set; }
        public long UserId { get; set; }
        public int Num { get; set; }
        public int Unit { get; set; }
        public int BetCent { get; set; }
        public int PricePer { get; set; }
        public int PrizeModel { get; set; }
        public Nullable<int> WinCent { get; set; }
        public System.DateTime OrderTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public int UserCurrentRebate { get; set; }
        public string PrizeModeFull { get; set; }
    
        public virtual PlayTogether PlayTogether { get; set; }
    }
}
