//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataRecovery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WithdrawDeposit
    {
        public long Id { get; set; }
        public int BankAccountId { get; set; }
        public int MoneyCent { get; set; }
        public int Status { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public Nullable<long> UserIdProcessedBy { get; set; }
        public Nullable<System.DateTime> ProcessedTime { get; set; }
        public string ProcessComment { get; set; }
    
        public virtual UserBankAccount UserBankAccount { get; set; }
    }
}
